services:
  web:
    build: .
    container_name: php-web-agencia
    ports:
      - "8110:80"
    volumes:
      - ../proyecto-php-agencia:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:11
    container_name: mariadb-agencia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agencia_php
      MYSQL_USER: guia
      MYSQL_PASSWORD: viaje123
    volumes:
      - ../db-agencia:/var/lib/mysql
    ports:
      - "3320:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-agencia
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: guia
      PMA_PASSWORD: viaje123
    ports:
      - "8111:80"
  browsersync:
    image: node:20-alpine
    container_name: browsersync-agencia
    working_dir: /app
    depends_on:
      - web
    volumes:
      - ../proyecto-php-agencia:/src
    command: sh -c "npm install -g browser-sync && browser-sync start --proxy 'web:80' --files '/src/**/*.*' --no-ui --host 0.0.0.0 --port 3002"
    ports:
      - "3002:3002"
